# Generated by Django 6.0.1 on 2026-02-10 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=50, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Defective', 'Defective'), ('Missing', 'Missing'), ('Condemned', 'Condemned')], default='Working', max_length=50)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('borrower_name', models.CharField(blank=True, max_length=100, null=True)),
                ('borrower_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('borrow_location', models.CharField(blank=True, choices=[('In-Campus', 'In-Campus (Room-to-Room)'), ('Outside', 'Outside (External Borrow)'), ('Transfer', 'Inter-Campus Transfer')], max_length=50, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('processor', models.CharField(blank=True, default='-', max_length=100, null=True)),
                ('ram', models.CharField(blank=True, default='-', max_length=50, null=True)),
                ('storage', models.CharField(blank=True, default='-', max_length=50, null=True)),
                ('has_charger', models.BooleanField(default=True, verbose_name='Original Charger / Power Adapter')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('Hand Tool', 'Hand Tool'), ('Consumable', 'Consumable'), ('Accessory', 'Accessory'), ('Computer Part', 'Computer Part'), ('Network', 'Network Equipment')], default='Hand Tool', max_length=50)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Defective', 'Defective'), ('Missing', 'Missing'), ('Condemned', 'Condemned')], default='Working', max_length=50)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('borrower_name', models.CharField(blank=True, max_length=100, null=True)),
                ('borrower_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('borrow_location', models.CharField(blank=True, choices=[('In-Campus', 'In-Campus (Room-to-Room)'), ('Outside', 'Outside (External Borrow)'), ('Transfer', 'Inter-Campus Transfer')], max_length=50, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Defective', 'Defective'), ('Missing', 'Missing'), ('Condemned', 'Condemned')], default='Working', max_length=50)),
                ('processor', models.CharField(blank=True, max_length=100)),
                ('ram', models.CharField(blank=True, max_length=50)),
                ('storage', models.CharField(blank=True, max_length=50)),
                ('graphics_card', models.CharField(blank=True, max_length=100)),
                ('has_monitor', models.BooleanField(default=True)),
                ('has_keyboard', models.BooleanField(default=True)),
                ('has_mouse', models.BooleanField(default=True)),
                ('has_avr', models.BooleanField(default=True)),
                ('is_borrowed', models.BooleanField(default=False)),
                ('borrower_name', models.CharField(blank=True, max_length=100, null=True)),
                ('borrower_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('borrow_location', models.CharField(blank=True, choices=[('In-Campus', 'In-Campus (Room-to-Room)'), ('Outside', 'Outside (External Borrow)'), ('Transfer', 'Inter-Campus Transfer')], max_length=50, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.room')),
            ],
        ),
    ]
