# Generated by Django 6.0.1 on 2026-02-12 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_personalcomputer_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.room'),
        ),
    ]
