# Generated by Django 6.0.1 on 2026-02-12 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_tool_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
