# Generated by Django 6.0.1 on 2026-02-12 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_laptop_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('Hand Tool', 'Hand Tool'), ('Consumable', 'Consumable'), ('Accessory', 'Accessory'), ('Computer Part', 'Computer Part'), ('Network', 'Network Equipment'), ('Office Supplies', 'Office Supplies'), ('Other', 'Other')], default='Hand Tool', max_length=50),
        ),
        migrations.AlterField(
            model_name='tool',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
