# Generated by Django 6.0.1 on 2026-02-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_tool_category_alter_tool_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcomputer',
            name='has_hdmi',
            field=models.BooleanField(default=True),
        ),
    ]
