# Generated by Django 6.0.1 on 2026-02-13 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_personalcomputer_has_hdmi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=100)),
                ('borrower_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('borrow_location', models.CharField(max_length=100)),
                ('quantity_borrowed', models.IntegerField(default=1)),
                ('date_borrowed', models.DateTimeField(auto_now_add=True)),
                ('return_due_date', models.DateField(blank=True, null=True)),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.tool')),
            ],
        ),
    ]
