# Generated by Django 6.0.1 on 2026-02-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_borroweditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='category',
            field=models.CharField(choices=[('Hand Tool', 'Hand Tool'), ('Consumable', 'Consumable'), ('Accessory', 'Accessory'), ('Computer Part', 'Computer Part'), ('Network', 'Network Equipment'), ('Office Supplies', 'Office Supplies'), ('Animation', 'Animation'), ('Other', 'Other')], default='Hand Tool', max_length=50),
        ),
    ]
