# Generated by Django 6.0.1 on 2026-02-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_tool_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='borroweditem',
            name='borrower_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borroweditem',
            name='borrower_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borroweditem',
            name='borrower_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='borroweditem',
            name='borrower_purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='borrower_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='borrower_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='borrower_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='borrower_purpose',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='borrower_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='borrower_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='borrower_position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='borrower_purpose',
            field=models.TextField(blank=True, null=True),
        ),
    ]
