# Generated by Django 6.0.1 on 2026-03-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_borroweditem_borrower_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcomputer',
            name='motherboard',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
