# Generated by Django 6.0.1 on 2026-03-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_personalcomputer_motherboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('Borrow', 'Borrow'), ('Return', 'Return'), ('Added', 'Added New Asset')], max_length=20)),
                ('item_details', models.CharField(max_length=255)),
                ('borrower_name', models.CharField(default='N/A', max_length=150)),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
