# Generated by Django 6.0.1 on 2026-04-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_transactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcomputer',
            name='has_vga',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='monitor_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
