# Generated by Django 6.0.1 on 2026-04-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_personalcomputer_has_vga_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcomputer',
            name='avr_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
