# Generated by Django 6.0.1 on 2026-04-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_personalcomputer_avr_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcomputer',
            name='keyboard_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='mouse_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
