# Generated by Django 6.0.1 on 2026-04-08 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_personalcomputer_keyboard_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='linked_pc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='pages.personalcomputer'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
