# Generated by Django 6.0.1 on 2026-04-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_tool_linked_pc_alter_tool_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcomputer',
            name='avr_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='graphics_card_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='keyboard_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='monitor_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='motherboard_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='mouse_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='processor_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='ram_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='storage_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tool',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
