# Generated by Django 6.0.1 on 2026-04-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_personalcomputer_avr_sn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcomputer',
            name='is_igpu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='ram_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='ram_2_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='ram_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='ram_3_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='ram_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='ram_4_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='storage_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='storage_2_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='storage_3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='storage_3_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='storage_4',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='storage_4_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
