# Generated by Django 6.0.4 on 2026-04-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0017_personalcomputer_is_igpu_personalcomputer_ram_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalcomputer',
            name='psu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personalcomputer',
            name='psu_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
