# Generated by Django 6.0.4 on 2026-04-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_personalcomputer_psu_personalcomputer_psu_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='unit_of_measure',
            field=models.CharField(choices=[('pcs', 'Pieces / Individuals'), ('box', 'Box(es)'), ('ream', 'Ream(s)'), ('pack', 'Pack(s)'), ('roll', 'Roll(s)'), ('bottle', 'Bottle(s)'), ('set', 'Set(s)')], default='pcs', max_length=20),
        ),
    ]
